export const skillsData = [
  "Excel proficiency",
  "External recruitment",
  "Payroll control",
  "Recruitment",
  "Salary review",
  "Employee Relations",
  "Employee record management",
  "HR policy renewal",
  "Leadership",
];

export const educationHistoryData = [
  {
    id: 1,
    institute: "St. Agnes College, Autonomous",
    course: "B. Com: Commerce",
    location: "Mangalore, India",
    startDate: "06/2014",
    endDate: "04/2017",
  },
  {
    id: 2,
    institute: "St. Agnes College, Karnataka State",
    course: "Pre-University: Commerce",
    location: "Mangalore, India",
    startDate: "06/2012",
    endDate: "04/2014",
  },
  {
    id: 3,
    institute: "Vishwamangala High School, Karnataka State",
    course: "High School Diploma",
    location: "Mangalore, India",
    startDate: null,
    endDate: "04/2012",
  },
];

export const workHistoryData = [
  {
    id: 1,
    companyName: "Silverstone Luxury Rent a Car",
    position: "HR Executive / Admin",
    location: "Dubai, UAE",
    startDate: "02/2024",
    endDate: "Current",
    points: [
      "Develop and implement HR strategies, policies, and procedures aligned with company's goals and objectives",
      "Oversee recruitment and selection process, including sourcing candidates, conducting interviews, and making hiring decisions",
      "Manage employee onboarding and orientation programs to ensure smooth integration into organization",
      "Administer employee benefits programs, including health insurance, retirement plans, and leave policies",
      "Handle employee relations issues, including conflict resolution, disciplinary actions, and performance management",
      "Coordinate training and development initiatives to enhance employee skills and competencies",
      "Ensure compliance with labor laws, regulations, and company policies related to employment practices",
      "Manage HR data and maintain accurate employee records using HRIS software",
      "Develop and implement employee engagement programs to foster positive work environment and improve employee morale",
      "Provide guidance and support to managers and employees on HR-related matters",
      "Monitor and evaluate HR metrics to assess effectiveness of HR programs and initiatives",
      "Stay updated on industry trends and best practices in HR management to drive continuous improvement",
      "Organized personal and professional calendars, supplying timely reminders of upcoming meetings and events",
      "Prepared meeting rooms and event spaces to achieve successful client engagements",
      "Purchased office supplies to maintain consistent inventory",
      "Booked flights and hotels for domestic and international meetings",
      "Improved business HR policies by guiding and collaborating with managers",
    ],
  },
  {
    id: 2,
    companyName: "MCA Auditing",
    position: "Corporate Services Executive, HR Assistant Cum Admin Executive",
    location: "Dubai, UAE",
    startDate: "12/2018",
    endDate: "12/2023",
    points: [
      "Managing client’s portfolios and handling their requests promptly",
      "Providing corporate assistance to potential and existing clients",
      "Performing general corporate administration duties",
      "Maintain and keep records of corporate files",
      "Maintaining an open dialogue of communication with clients regularly and ensuring a balanced turn-around time with satisfactory results",
      "Collaboratively assisting in setting up of new companies, preparation, and submission of the necessary documents",
      "Support HR functions including recruitment, onboarding, and offboarding processes",
      "Manage employee records and maintain HR databases and filing systems",
      "Coordinate with candidates and schedule interviews, meetings, and training sessions",
      "Assist in drafting HR-related documents such as offer letters, contracts, and policies",
      "Handle employee queries regarding HR policies, benefits, and procedures",
      "Coordinate employee engagement activities and events",
      "Assist in payroll processing and maintain attendance records",
      "Monitor office supplies inventory and place orders as needed",
      "Assist in travel arrangements and visa processing for employees",
      "Provide general administrative support to the office, including managing correspondence and handling phone calls",
    ],
  },
  {
    id: 3,
    companyName: "IDP Dubai",
    position: "IELTS Exam Supervisor (Part Time)",
    location: "Dubai, UAE",
    startDate: "06/2021",
    endDate: "05/2022",
    points: [
      "Ensure the smooth administration of the IELTS exam according to British Council guidelines and standards",
      "Set up exam venues, including arranging seating arrangements, checking equipment, and ensuring conducive environment for candidates",
      "Verify identity of candidates and ensure compliance with exam regulations and security protocols",
      "Distribute exam materials, such as test booklets and answer sheets, and collect completed papers at the end of each session",
      "Monitor candidates during exam to prevent cheating or misconduct and address any irregularities promptly",
      "Provide instructions to candidates regarding exam procedures, timing, and rules",
      "Handle any technical issues or emergencies that may arise during exam, such as equipment malfunction or candidate illness",
      "Maintain accurate records of exam attendance, incidents, and any special accommodations provided to candidates",
      "Collaborate with other exam supervisors and invigilators to coordinate exam logistics and ensure integrity and fairness of exam process",
      "Communicate with exam administrators, test centers, and relevant authorities as needed to report exam outcomes and address any issues or concerns",
      "Participate in training sessions and meetings to stay updated on exam policies, procedures, and best practices",
    ],
  },
  {
    id: 4,
    companyName: "DXC Technology",
    position: "Insurance Claims Examiner",
    location: "Bangalore, India",
    startDate: "07/2017",
    endDate: "08/2018",
    points: [
      "Review insurance claims to ensure compliance with policy terms and conditions",
      "Investigate claim circumstances by gathering information from various sources",
      "Evaluate policy coverage to determine the extent of liability",
      "Verify claimed losses through thorough assessment of evidence",
      "Maintain communication with stakeholders throughout the claims process",
      "Negotiate settlements that consider policy coverage and applicable regulations",
      "Document all aspects of claims assessment process accurately",
      "Ensure compliance with legal and regulatory requirements",
      "Collaborate with underwriters to provide insights into claims trends",
      "Identify opportunities for process improvement and efficiency enhancement",
    ],
  },
];
